//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WillPower.Sunkenland.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WillPower.Sunkenland.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE AT YOUR OWN RISK!
        ///
        ///Code Copyright © 2023, Will `Willow&apos; Osborn.                                                    
        ///                                                                                                
        ///This code is provided &apos;AS IS, NO WARRANTY&apos; and is intended for no specific use or person.       
        ///In fact, the code herein is so confuggled, it should not be used by ANYONE EVER and ANYTHING that happens as a result of its use is COMPLETELY and UTTERLY YOUR FAULT.  :p                   
        ///Yo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Items&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;-Empty-&quot;,
        ///      &quot;Description&quot;: &quot;Nothing&quot;,
        ///      &quot;MaxStack&quot;: 1,
        ///      &quot;itemID&quot;: -1,
        ///      &quot;amount&quot;: 0,
        ///      &quot;condition&quot;: 100,
        ///      &quot;isCombinedWithItem&quot;: false,
        ///      &quot;itemProperties&quot;: []
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;50 Caliber Ammunition&quot;,
        ///      &quot;Description&quot;: &quot;50 Caliber Ammunition&quot;,
        ///      &quot;MaxStack&quot;: 60,
        ///      &quot;itemID&quot;: 1,
        ///      &quot;amount&quot;: 0,
        ///      &quot;condition&quot;: 100,
        ///      &quot;isCombinedWithItem&quot;: false,
        ///      &quot;itemProperties&quot;: []
        ///    },
        ///    {
        ///      &quot;N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameData {
            get {
                return ResourceManager.GetString("GameData", resourceCulture);
            }
        }
    }
}
